INSERT INTO public.genre(name) VALUES ('Fantasy');
INSERT INTO public.genre(name) VALUES ('Mystery');        
INSERT INTO public.genre(name) VALUES ('Romance');        
INSERT INTO public.genre(name) VALUES ('Science Fiction');
INSERT INTO public.genre(name) VALUES ('Thriller');       
INSERT INTO public.genre(name) VALUES ('Suspense');       
INSERT INTO public.genre(name) VALUES ('Western');        
INSERT INTO public.genre(name) VALUES ('Action');
INSERT INTO public.genre(name) VALUES ('Adventure');      
INSERT INTO public.genre(name) VALUES ('Classics');      
INSERT INTO public.genre(name) VALUES ('Comic Book');    
INSERT INTO public.genre(name) VALUES ('Graphic Novel'); 
INSERT INTO public.genre(name) VALUES ('Historical Fiction');
INSERT INTO public.genre(name) VALUES ('Horror');
INSERT INTO public.genre(name) VALUES ('Literary Fiction');
INSERT INTO public.genre(name) VALUES ('Non-Fiction');