INSERT INTO public.genre(id, name) VALUES ('1', 'Fantasy');
INSERT INTO public.genre(id, name) VALUES ('2', 'Mystery');        
INSERT INTO public.genre(id, name) VALUES ('3', 'Romance');        
INSERT INTO public.genre(id, name) VALUES ('4', 'Science Fiction');
INSERT INTO public.genre(id, name) VALUES ('5', 'Thriller');       
INSERT INTO public.genre(id, name) VALUES ('6', 'Suspense');       
INSERT INTO public.genre(id, name) VALUES ('7', 'Western');        
INSERT INTO public.genre(id, name) VALUES ('8', 'Action');
INSERT INTO public.genre(id, name) VALUES ('9', 'Adventure');      
INSERT INTO public.genre(id, name) VALUES ('10', 'Classics');      
INSERT INTO public.genre(id, name) VALUES ('11', 'Comic Book');    
INSERT INTO public.genre(id, name) VALUES ('12', 'Graphic Novel'); 
INSERT INTO public.genre(id, name) VALUES ('13', 'Historical Fiction');
INSERT INTO public.genre(id, name) VALUES ('14', 'Horror');
INSERT INTO public.genre(id, name) VALUES ('15', 'Literary Fiction');
INSERT INTO public.genre(id, name) VALUES ('16', 'Non-Fiction');